#pragma once

enum MESSAGE_TYPES : uint8_t
{
    MESSAGE_TYPE_UNKNOWN = 0x00,
    MESSAGE_TYPE_LOCATION = 0x01,

    MESSAGE_TYPE_DISTRESS = 0x10,
    MESSAGE_TYPE_HIT = 0x11,
    MESSAGE_TYPE_RESPAWNED = 0x12,

    MESSAGE_TYPE_DEVICE_INFO = 0x50
};